name: Windows Validation

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.275.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Tools, shaderc
          vulkan-use-cache: true
      - name: Build
        run: |
          $env:VCPKG_ROOT=""
          cmake -S . -B "build/x64" -G "Visual Studio 17 2022" -T v143 -A x64 -DCMAKE_BUILD_TYPE=Release
          cmake --build ./build/x64
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: starship-windows
          path: ./build/x64/Debug
          retention-days: 1